### ISSUE TITLE
PermissionHandlerOhos.openAppSettings();

### ISSUE THREAD

**Issue by jinliyuelong** [HarmonyCandies/permission_handler_ohos#1]
PermissionHandlerOhos.openAppSettings();
执行跳转后，设置页面空白

**Comment by jinliyuelong** [comment]
PermissionStatusOhos permission = await PermissionHandlerOhos.requestPermission(PermissionOhos.store_persistent_data.name);
这个没有弹出请求弹窗
 返回得status 是 PermissionStatusOhos.invalid

**Comment by jinliyuelong** [comment]
可以关闭了，忘记加 { name: "ohos.permission.CAMERA" },
      { name: "ohos.permission.STORE_PERSISTENT_DATA" },

**Comment by zmtzawqlp** [comment]
有些权限枚举里面可能没有。可以自己传字符串过去。harmony 和openharmony权限区别蛮大的
